version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0"
    networks:
      - azfnnet

  functionapp:
    build: .
    container_name: qdeck-model-runner
    environment:
      AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      FUNCTIONS_WORKER_RUNTIME: "python"
      Storage: "UseDevelopmentStorage=true"
    depends_on:
      - azurite
    ports:
      - "8080:80"
    networks:
      - azfnnet

networks:
  azfnnet:
